# Generated by Django 2.2.4 on 2019-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('datahora', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('valor', models.IntegerField()),
                ('vendedor', models.CharField(max_length=50)),
            ],
        ),
    ]
